### ISSUE TITLE
SiemensS7-Bootloader can't dump S7 PLC RAM

### ISSUE THREAD

**Issue by wmsuper** [RUB-SysSec/SiemensS7-Bootloader#1]
First of all, thank you for your work.
In order to get the decompressed firmware code,I dumped the memory of S7 PLC.
But the memory data is not valid ARM machine code except the bootloader.
Here are my steps:

1.Turn on the PLC for 30s.
2.Reset the PLC(turn off the PLC,then turn on it,about 1s).
3.Use the tool to dump RAM.

I guess it may be due to data loss immediately after SDRAM power off.
Do you have a good solution?
Thank you.

**Comment by framuga** [comment]
Attempted to inject the MFGT1 string within the 0.5-second window using several automata. 1211C v3.0, 1212C v4.2.7 unsuccessfully. 38400 baud, 8-bit.
Am I missing something?
Can you provide details on anything not already documented to achieve the initial connection to the bootloader?
